version: 2
updates:

  # Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Library
  - package-ecosystem: nuget
    directory: /JsonExtensions/
    schedule:
      interval: monthly

  # Examples
  - package-ecosystem: nuget
    directory: /JsonExtensions.Examples/
    schedule:
      interval: monthly

  # Tests
  - package-ecosystem: nuget
    directory: /JsonExtensions.Tests/
    schedule:
      interval: monthly
