version: 2
updates:

  # Workflows
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly

  # Library
  - package-ecosystem: nuget
    directory: /Library/
    schedule:
      interval: monthly

  # Examples
  - package-ecosystem: nuget
    directory: /Examples/
    schedule:
      interval: monthly
