name: Build

on:
  push:
    paths:
    - '**.cs'
    - '**.csproj'
    - '**.sln'
    - '.github/workflows/build.yml'
    branches:
    - '**'
    tags:
    - '*.*.*'
  pull_request:
    branches:
    - '**'
  workflow_dispatch:

jobs:
  library:
    name: Library
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      packages: write

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore Library

    - name: Build Library
      run: dotnet build --configuration Release --no-restore Library

    - name: Run Tests
      run: dotnet test --configuration Release --no-build Library

    - name: Package Library
      run: dotnet pack --configuration Release --no-build Library

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: viral32111.JsonExtensions
        path: |
          ./Library/bin/Release/net6.0/viral32111.JsonExtensions.dll
          ./Library/bin/Release/net6.0/viral32111.JsonExtensions.deps.json
          ./Library/bin/Release/viral32111.JsonExtensions.*.nupkg

    - name: Add GitHub Packages Source
      if: ${{ github.ref_type == 'tag' && github.event_name != 'pull_request' }}
      run: |
        dotnet nuget add source \
          --name github \
          --username ${{ github.repository_owner }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          --store-password-in-clear-text \
          "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"

    - name: Upload Package
      if: ${{ github.ref_type == 'tag' && github.event_name != 'pull_request' }}
      run: |
        dotnet nuget push \
          --source github \
          --skip-duplicate \
          --api-key ${{ secrets.GITHUB_TOKEN }} \
          ./Library/bin/Release/viral32111.JsonExtensions.*.nupkg

    - name: Create Release
      if: ${{ github.ref_type == 'tag' && github.event_name != 'pull_request' }}
      uses: softprops/action-gh-release@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.ref_name }}
        draft: true
        files: |
          ./Library/bin/Release/net6.0/viral32111.JsonExtensions.dll
          ./Library/bin/Release/viral32111.JsonExtensions.${{ github.ref_name }}.nupkg

  test:
    name: Test
    runs-on: ubuntu-22.04
    needs: library
    permissions:
      contents: read

    steps:
    - name: Clone Repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x

    - name: Restore Dependencies
      run: dotnet restore Examples

    - name: Build Project
      run: dotnet build --configuration Release --no-restore Examples

    - name: Run Tests
      run: dotnet test --configuration Release --no-build Examples

    - name: Launch Project
      run: |
        cd ./Examples/
        dotnet run --configuration Release --no-build

    - name: Upload Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: Examples
        path: |
          ./Examples/bin/Release/net6.0/Examples.dll
          ./Examples/bin/Release/net6.0/Examples.deps.json
          ./Examples/bin/Release/net6.0/Examples.runtimeconfig.json
